### ISSUE TITLE
vm.max_map_count is too low

### ISSUE THREAD

**Issue by tsn77130** [pires/kubernetes-elasticsearch-cluster#137] opened 2017-09-29 10:02 UTC
Hi Paulo,

Despite of initcontainer config, I sometimes have floowing error message in my containers (here on data persistant node in statefulset)

Do you know from what it could come from ?
```

ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2017-09-29T09:33:20,559][INFO ][o.e.n.Node               ] [es-data1-0] stopping ...
[2017-09-29T09:33:20,605][INFO ][o.e.n.Node               ] [es-data1-0] stopped
[2017-09-29T09:33:20,606][INFO ][o.e.n.Node               ] [es-data1-0] closing ...
[2017-09-29T09:33:20,624][INFO ][o.e.n.Node               ] [es-data1-0] closed

```

I run ES on top of 1.7.6 K8S cluster

**Comment by pires** [comment] 2017-09-29 10:20
Maybe the initcontainer _failed_? I honestly don't know.

**Comment by camechis** [comment] 2017-10-25 15:40
Think I just ran into this myself on GKE.  Same error.

**Comment by pires** [comment] 2017-10-25 16:13
This seems a duplicate of https://github.com/pires/kubernetes-elasticsearch-cluster/issues/85.

**Closed by pires** 2017-10-25 16:13 UTC
