### ISSUE TITLE
Pods status go into CrashLoopBackOff

### ISSUE THREAD

**Issue by asaf** [pires/kubernetes-elasticsearch-cluster#52] opened 2016-08-10 18:10 UTC
Hey,

I'm trying to setup an ES using this repo,

I made some tweaks though
1) I activated data/client in the `es-master` deployment
2) I activated client in the `es-data` deployment

I created 1 instance of master and 1 instance of data,

Both PODs became running and ES recognizes both nodes in the cluster,

Once I tried to shutdown one of the nodes the whole thing got broken,

This is what I see:
```bash
es-data-...     1/1       Running            6          17m
es-master-...   0/1       CrashLoopBackOff   6          1h
```

After a while both become running:

```bash
es-data-...    1/1       Running   6          20m
es-master-...   1/1       Running   7          1h
```

Then few seconds after the data crashes:

```bash
notebook:kub me$ kubectl get pods
NAME                         READY     STATUS             RESTARTS   AGE
es-data-...     0/1       CrashLoopBackOff   6          20m
es-master-...   1/1       Running            7          1h
```

The best error I can see when running `kubectl describe pod es-data...` is this one:

```bash
  19m	6s	30	{kubelet 172.17.8.102}	spec.containers{es-data}	Warning	BackOff		Back-off restarting failed docker container
  48s	6s	4	{kubelet 172.17.8.102}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "es-data" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=es-data pod=es-data-2599720219-u9axv_default(330fb913-5f22-11e6-be3c-080027e9ede8)"
```

Or in master (seems to be the same)

```bash
  5m	10s	22	{kubelet 172.17.8.102}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "es-master" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=es-master pod=es-master-2585506078-as9kp_default(7b7095c8-5f1b-11e6-be3c-080027e9ede8)"
```

First, I'm not sure if this is ok to make the _master_ node also a _client_ and a _data_ plus make the _data_ a _client_ as well, this should work at all? I'd like to start with a small cluster as possible and scale on time, should it work?

If so, any clue why it is acting that way?

Thanks,

Asaf

**Comment by pires** [comment] 2016-08-10 18:17
>  I'm not sure if this is ok to make the master node also a client and a data plus make the data a client as well

Elasticsearch documentation disrecommend this practice.

Other than that, we need to see pod logs to understand why it's crashing.

**Comment by asaf** [comment] 2016-08-10 19:57
ye but a single server that perform all roles actually work just fine,
I was more wondering whether the _fabric8io_ unicast discovery should work when multiple roles are activated at once,

There are no errors.....

The only thing I see is this:

```bash
kubectl describe pod es-data-2599720219-u9axv
  2h	8m	25	{kubelet 172.17.8.102}	spec.containers{es-data}	Normal	Pulling		pulling image "quay.io/pires/docker-elasticsearch-kubernetes:2.3.4"
  2h	8m	25	{kubelet 172.17.8.102}	spec.containers{es-data}	Normal	Pulled		Successfully pulled image "quay.io/pires/docker-elasticsearch-kubernetes:2.3.4"
  8m	8m	1	{kubelet 172.17.8.102}	spec.containers{es-data}	Normal	Created		Created container with docker id 817f72bd6eea
  8m	8m	1	{kubelet 172.17.8.102}	spec.containers{es-data}	Normal	Started		Started container with docker id 817f72bd6eea
  1h	12s	81	{kubelet 172.17.8.102}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "es-data" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=es-data pod=es-data-2599720219-u9axv_default(330fb913-5f22-11e6-be3c-080027e9ede8)"

  2h	12s	182	{kubelet 172.17.8.102}	spec.containers{es-data}	Warning	BackOff	Back-off restarting failed docker container
```

Any suggestions how to debug further?

Many thanks.

**Comment by pires** [comment] 2016-08-10 20:01
`kubectl logs <pod>`

**Comment by asaf** [comment] 2016-08-10 20:23
yea well, same thing, nothing that seems to be suspicious (same errors as in describe)

I also tried to take a look at /data/log/.. but nothing,

Anyway, I keep this issue opened for a while, meanwhile I'll try to investigate it a bit more,


Thanks.

**Comment by tspacek** [comment] 2016-08-24 11:33
@asaf Did you get to the bottom of this? I get the same. I suspect because I am using https://github.com/kubernetes/minikube

**Comment by pires** [comment] 2016-08-24 11:45
@tspacek this may be something else, namely the default value for `ES_HEAP_SIZE`. I will be validating that ASAP.

**Comment by pires** [comment] 2016-08-24 12:14
I can confirm this happens, pods are killed. Need to make sure why, though. My gut feeling is OOM.

**Comment by tspacek** [comment] 2016-08-24 12:18
Can confirm it's stable if I set `ES_HEAP_SIZE` such that the sum of all pods' is lower than Minikube's default 1gb.

**Comment by pires** [comment] 2016-08-24 12:39
@tspacek can confirm as well that's the case. I will be closing this by setting a very low value, `256MB` and adding a note on docs.

**Comment by pires** [comment] 2016-08-24 12:47
@asaf try again and let us know!

**Closed** 2016-08-24 12:46 UTC
Labels: bug, help wanted

**Comment by HagaiBarel** [comment] 2016-11-17 11:16
Just want to share my experience with this, 
had the same issue, 4 hyper-v vm's with 1gb RAM each. Had random crashes all over the es cluster.  I allocated 2gb Ram to each machine, crashes stop and the es cluster runs stable.
